### ISSUE TITLE
Looking for legacy code for comparison and better understanding

### ISSUE THREAD

**Issue by lee1043** [CDAT/wk#10]
https://github.com/CDAT/wk/blob/2b953281c7a4c5d0ac2d79fcc3523113e31613d5/WK/process.py#L191

Hi @doutriaux1 , do you have the original legacy code for this part (line 191-201) of the code? I guess it might be the Wheeler's Fortran code. While I have modified version of it, I cannot find the original one. Just wanted to see which part of its Fortran code is corresponding to this part, for better understanding of the code.

**Comment by doutriaux1** [comment]
sorry, it's long long gone. But it's based on the version of fortran at the time the paper was first published. Hope this helps.

**Comment by lee1043** [comment]
@doutriaux1 that helps. Thanks!
